language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - pip install -r requirements.txt

script: pytest --cov=discogs_client/ --cov-report=term-missing --cov-config .coveragerc

after_success:
    - coveralls
